### ISSUE TITLE
Unmatching model names

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-sphire#123]
When running 'scipion installb cryolo_model'

the dowloaded model is saved as: cryolo_model-202005_nn_N63_c17/gmodel_phosnet_202005_nn_N63_c17.h5

while the expected file name by the protocol is: cryolo_model-202005_N63_c17/gmodel_phosnet_202005_N63_c17.h5

Linking the file to a renamed file and folder solved the issue.

**Comment by azazellochg** [comment]
These are different models! "nn" is janni-denoised

**Comment by azazellochg** [comment]
installb downloads both models: https://github.com/scipion-em/scipion-em-sphire/blob/master/sphire/__init__.py#L152 by default

**Comment by fede-pe** [comment]
scipion3 installb cryolo_model 

is only installing  cryolo_model-202005_nn_N63_c17 to me

**Comment by azazellochg** [comment]
ok, I'll have a look. Thanks!

**Comment by azazellochg** [comment]
I see the problem. Installp should install both models with the plugin, since they both have default=True flag. However, installb will install only one of them, because both binaries are called "cryolo_model" and the difference is the "version". I don't see any workaround for this without changing model/vars names that will break backwards compatibility.

**Comment by fede-pe** [comment]
I see, is there a manual way to download the models from terminal (wget or similar)? I am just missing the models I would rather not reinstall the plugin

**Comment by azazellochg** [comment]
of course, "scipion3 installb cryolo_model-202005_N63_c17" will do it

**Comment by fede-pe** [comment]
great! thanks grigory
